webpizza/applipizza/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from applipizza import views

urlpatterns = [
    path('pizzas/', views.pizzas),
    path('ingredients/', views.ingredients),
    path('pizzas/<int:pizza_id>/', views.pizza),
    path('ingredients/add/', views.formulaireCreationIngredient),
    path('ingredients/create/', views.creerIngredient),
    path('pizzas/add/', views.formulaireCreationPizza),
    path('pizzas/create/', views.creerPizza),
    path('pizzas/<int:pizza_id>/addIngredient/', views.ajouterIngredientDansPizza),
    path('pizzas/<int:pizza_id>/delete/', views.supprimerPizza),
    path('pizzas/<int:pizza_id>/update/', views.afficherFormulaireModificationPizza),
    path('pizzas/<int:pizza_id>/updated/', views.modifierPizza),
    path('ingredients/<int:ingredient_id>/delete/', views.supprimerIngredient),
    path('ingredients/<int:ingredient_id>/update/', views.afficherFormulaireModificationIngredient),
    path('ingredients/<int:ingredient_id>/updated/', views.modifierIngredient),
    path('pizzas/<int:pizza_id>/deleteIngredient/<int:composition_id>/', views.supprimerIngredientDansPizza),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

webpizza/webpizza/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('applipizza.urls')),
    path('', include('applicompte.urls')),
    path('', include('applipanier.urls')),
]

webpizza/applipizza/models.py
from django.db import models

# Create your models here.

class Ingredient(models.Model) :

    # idIngredient est une clé primaire, n auto-increment => AutoField
    idIngredient = models.AutoField(primary_key = True)

    # nomIngredient est une chaine de caractère = CharField
    nomIngredient = models.CharField(max_length = 50, verbose_name = 'le nom de cet ingrédient')

    # une mthode de type 'toString'
    def __str__(self) -> str :
        return self.nomIngredient
    
class Pizza(models.Model) :

    # idPizza est une clé primaire, n auto-increment => AutoField
    idPizza = models.AutoField(primary_key = True)

    # nomPizza est une chaine de caractère = CharField
    nomPizza = models.CharField(max_length = 50, verbose_name = 'le nom de cette pizza')
    
    # le prix est décimal, maximum = 4 chiffres, dont 2 décimales
    prix = models.DecimalField(max_digits = 4, decimal_places = 2, verbose_name = 'le prix')

    # fichier image de la pizza
    image = models.ImageField(default = 'imagesPizzas/default.PNG', upload_to = 'imagesPizzas/')

    # une mthode de type 'toString'
    def __str__(self) -> str :
        return 'pizza ' + self.nomPizza + ' (prix : ' + str(self.prix) + ' €)'

class Composition(models.Model) :

    # la classe Meta qui gère l'unicité du couple de clés étrangères
    class Meta :
        unique_together = ('ingredient', 'pizza') # le nom des champs clés étrangères

    # idComposition est une clé primaire
    idComposition = models.AutoField(primary_key = True)

    # les deux champs clés étrangères, dont les noms correspondent aux classe respectives en minuscule
    ingredient = models.ForeignKey(Ingredient, on_delete = models.CASCADE)
    pizza = models.ForeignKey(Pizza, on_delete = models.CASCADE)
    
    # l'autre champ, chaine de caractères
    quantite = models.CharField(max_length = 100, verbose_name = 'la quantité')

    # une mthode de type 'toString'
    def __str__(self) -> str :
        ing = self.ingredient
        piz = self.pizza
        return ing.nomIngredient + ' fait partie de la pizza ' + piz.nomPizza + ' (quantité : ' + self.quantite + ')'

webpizza/applipizza/forms.py
from django import forms
from django.forms import ModelForm
from applipizza.models import Ingredient, Pizza, Composition

class IngredientForm(ModelForm) :
    class Meta :
        model = Ingredient
        fields = ['nomIngredient']

### Version non automatique
# class IngredientForm(forms.Form) :
#     nomIngredient = forms.CharField(
#         label = 'nom de cet ingrédient',
#         max_length = 50
#     )
###

class PizzaForm(ModelForm) :
    class Meta :
        model = Pizza
        fields = ['nomPizza','prix']

class CompositionForm(ModelForm) :
    class Meta :
        model = Composition
        fields = ['ingredient','quantite']

webpizza/applipizza/views.py
from django.shortcuts import render

# import des modèles
from applipizza.models import Pizza, Ingredient, Composition
from applipizza.forms import IngredientForm, PizzaForm, CompositionForm
from django.contrib.auth.models import User
from applicompte.models import PizzaUser

# Create your views here.
def pizzas(request) :
    user = None
    if request.user.is_authenticated :
        user = PizzaUser.objects.get(id = request.user.id)

    # récupération des pizzas de la base de données avec les mêmes instructions que dans le shell
    lesPizzas = Pizza.objects.all()

    # on retourne l'emplacement du template et, même s'il ne pas cette fois, le paramètre request, ainsi que le contenu calculé (lesPizzas) sout forme d'un dictionnaire python
    return render(
        request,
        'applipizza/pizzas.html',
        {'pizzas' : lesPizzas, 'user' : user}
    )

def ingredients(request) :
    # création du user
    user = None

    # cas d'un utilisateur staff
    if request.user.is_staff :
        lesIngredients = Ingredient.objects.all()
        user = PizzaUser.objects.get(id = request.user.id)
        return render(
            request,
            'applipizza/ingredients.html',
            {'ingredients' : lesIngredients, "user" : user}
        )

    # cas d'un client connecté
    elif request.user.is_authenticated :
        lesPizzas = Pizza.objects.all()
        user = PizzaUser.objects.get(id = request.user.id)
        return render(
            request,
            'applipizza/pizzas.html',
            {'pizzas' : lesPizzas, "user" : user}
        )
    
    # cas d'un internaute non connecté
    else :
        return render(
            request,
            'applicompte/login.html',
        )

def pizza(request, pizza_id) :
    user = None
    if request.user.is_authenticated :
        user = PizzaUser.objects.get(id = request.user.id)

    # récupération de la pizza dont l'id a été passé en paramètre (int:pizza_id)
    laPizza = Pizza.objects.get(idPizza = pizza_id)
    # récupération de la composition de la pizza dont l'id a été passé en paramètre (int:pizza_id)
    laCompo = Composition.objects.filter(pizza = pizza_id)

    lesIngredients = Ingredient.objects.all()

    # on retourne l'emplacement du template et de la pizza récup dans la base de données
    return render(
        request,
        'applipizza/pizza.html',
        {'pizza' : laPizza,
         'compo' : laCompo,
         'lesIng' : lesIngredients,
         'user' : user}
    )

def formulaireCreationIngredient(request) :
    # création du user
    user = None

    # cas d'un utilisateur staff
    if request.user.is_staff :
        user = PizzaUser.objects.get(id = request.user.id)
        # on retourne l'emplacement du template
        return render(
            request,
            'applipizza/formulaireCreationIngredient.html',
            { "user" : user }
        )

    # cas d'un client connecté
    elif request.user.is_authenticated :
        lesPizzas = Pizza.objects.all()
        user = PizzaUser.objects.get(id = request.user.id)
        return render(
            request,
            'applipizza/pizzas.html',
            {'pizzas' : lesPizzas, "user" : user}
        )
    
    # cas d'un internaute non connecté
    else :
        return render(
            request,
            'applicompte/login.html',
        )

def creerIngredient(request) :
    # création du user
    user = None

    # cas d'un utilisateur staff
    if request.user.is_staff :
        # récupération du formulaire posté
        form = IngredientForm(request.POST)

        if form.is_valid() :
            # récupération de la valeur du champ 'nomIngredient' 
            # form.cleaned_data permet de nettoyer la donnée au cas où des injections en tout genre seraient présentes
            nomIng = form.cleaned_data['nomIngredient']

            # création d'un nouvel ingrédient
            ing = Ingredient()

            # affectation de l'ingrédient dans la base
            ing.nomIngredient = nomIng

            # engregistrement de l'ingrédient dans la base
            ing.save()

        user = PizzaUser.objects.get(id = request.user.id)
        # on retourne l'emplacement du template
        return render(
            request,
            'applipizza/traitementFormulaireCreationIngredient.html',
            {"nom" : nomIng, "user" : user}
        )

    # cas d'un client connecté
    elif request.user.is_authenticated :
        lesPizzas = Pizza.objects.all()
        user = PizzaUser.objects.get(id = request.user.id)
        return render(
            request,
            'applipizza/pizzas.html',
            {'pizzas' : lesPizzas, "user" : user}
        )
    
    # cas d'un internaute non connecté
    else :
        return render(
            request,
            'applicompte/login.html',
        )

def formulaireCreationPizza(request) :
    # création du user
    user = None

    # cas d'un utilisateur staff
    if request.user.is_staff :
        user = PizzaUser.objects.get(id = request.user.id)
        # on retourne l'emplacement du template
        return render(
            request,
            'applipizza/formulaireCreationPizza.html',
            { "user" : user }
        )

    # cas d'un client connecté
    elif request.user.is_authenticated :
        lesPizzas = Pizza.objects.all()
        user = PizzaUser.objects.get(id = request.user.id)
        return render(
            request,
            'applipizza/pizzas.html',
            {'pizzas' : lesPizzas, "user" : user}
        )
    
    # cas d'un internaute non connecté
    else :
        return render(
            request,
            'applicompte/login.html',
        )

def creerPizza(request) :
    # création du user
    user = None

    # cas d'un utilisateur staff
    if request.user.is_staff :
        user = PizzaUser.objects.get(id = request.user.id)
        # récupération du formulaire posté
        form = PizzaForm(request.POST)

        if form.is_valid() :
            # création d'une nouvelle pizza
            piz = Pizza()

            # récupération de la valeur du champ 'nomPizza' 
            # form.cleaned_data permet de nettoyer la donnée au cas où des injections en tout genre seraient présentes
            piz.nomPizza = form.cleaned_data['nomPizza']
            piz.prix = form.cleaned_data['prix']
            piz.image = request.FILES['image']

            # engregistrement de la pizza dans la base
            piz.save()

        # on retourne l'emplacement de la vue (ou plutôt du template, au sens de django) et le contenu calculé, sous forme d'un dictionnaire python
        return render(
            request,
            'applipizza/traitementFormulaireCreationPizza.html',
            { "nom" : piz.nomPizza, "user" : user }
        )

    # cas d'un client connecté
    elif request.user.is_authenticated :
        lesPizzas = Pizza.objects.all()
        user = PizzaUser.objects.get(id = request.user.id)
        return render(
            request,
            'applipizza/pizzas.html',
            {'pizzas' : lesPizzas, "user" : user}
        )
    
    # cas d'un internaute non connecté
    else :
        return render(
            request,
            'applicompte/login.html',
        )

def ajouterIngredientDansPizza(request, pizza_id) :
    # création du user
    user = None

    # cas d'un utilisateur staff
    if request.user.is_staff :
        # récupération du formulaire posté
        formulaire = CompositionForm(request.POST)

        if formulaire.is_valid() :
            # récupération de la valeur du champ 'nomPizza' 
            # form.cleaned_data permet de nettoyer la donnée au cas où des injections en tout genre seraient présentes
            ing = formulaire.cleaned_data['ingredient']
            qte = formulaire.cleaned_data['quantite']
            piz = Pizza.objects.get(idPizza = pizza_id)
            compoPizza = Composition.objects.filter(pizza = pizza_id)
            lesIngredientsDeLaPizza = ((ligne.ingredient) for ligne in compoPizza)

            if ing in lesIngredientsDeLaPizza :
                compo = Composition.objects.filter(pizza = pizza_id, ingredient = ing)
                compo.delete()

            # création de la nouvelle instance de Composition et remplissage des attributs
            compo = Composition()
            compo.ingredient = ing
            compo.pizza = piz
            compo.quantite = qte
            # sauvegrade dans la base de la composition
            compo.save()

        # recupération de tous les ingrédients pour construire le futur select
        lesIngredients = Ingredient.objects.all()
        # actualisation des ingrédeitns entrant dans la composition de la pizza
        compoPizza = Composition.objects.filter(pizza = pizza_id)
        # on crée une liste dont chaque item contiendra l'identifiant de la composition (idComposition),
        # le nom de l'ingrédient et la quantité del i'ngrédeint dans cette composition
        listeIngredients = []
        for ligneCompo in compoPizza :
            # on récupère l'Ingredient pour utiliser son nomIngredient
            ingredient = Ingredient.objects.get(idIngredient = ligneCompo.ingredient.idIngredient)
            listeIngredients.append(
                {"idComposition" : ligneCompo.idComposition, "nom" : ingredient.nomIngredient, "qte" : ligneCompo.quantite}
            )
        user = PizzaUser.objects.get(id = request.user.id)
        # on retourne l'emplacement du template
        return render(
            request,
            'applipizza/pizza.html',
            {"pizza" : piz, "liste" : listeIngredients, "compo" : compoPizza, "lesIng" : lesIngredients, "user" : user}
        )

    # cas d'un client connecté
    elif request.user.is_authenticated :
        lesPizzas = Pizza.objects.all()
        user = PizzaUser.objects.get(id = request.user.id)
        return render(
            request,
            'applipizza/pizzas.html',

webpizza/applipizza/templates/applipizza/base.html
{% load static %}
<!DOCTYPE html> 
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css">
        <link rel="stylesheet" href="{% static 'applipizza/css/styles.css' %}">
        <link rel="icon" href="{% static 'applipizza/img/icon2.png' %}">
        <title>{% block title %}{% endblock %}</title>
    </head>
    <body class="Site">
        <header>
            {% if user.is_staff %}
            {% include 'applicompte/menuStaff.html' %}
            {% elif user.is_authenticated %}
            {% include 'applicompte/menuClient.html' %}
            {% else %}
            {% include 'applicompte/menuNonConnecte.html' %}
            {% endif %}
        </header>
        <main class="Site-content">
            {% block main %}{% endblock %}
        </main>
        <footer>
            {% include 'applipizza/footer.html' %}
        </footer>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    </body>
</html>

webpizza/applipizza/templates/applipizza/footer.html
© Appli Pizza 2023

webpizza/applipizza/templates/applipizza/formulaireCreationIngredient.html
{% extends 'applipizza/base.html' %}

{% block title %}
Création d'un ingrédient
{% endblock %}

{% block main %}
<h2>Création d'un ingrédient</h2>
<form action="/ingredients/create/" method="post">
    {% csrf_token %}
    <div class="mb-3">
        <label for="id_nomIngredient" class="form-label">Le nom de cet ingrédient</label>
        <input type="text" name="nomIngredient" class="form-control" maxlength="50" required id="id_nomIngredient">
    </div>
    <button type="submit" class="btn btn-primary">Envoyer</button>
</form>
{% endblock %}

webpizza/applipizza/templates/applipizza/formulaireCreationPizza.html
{% extends 'applipizza/base.html' %}

{% block title %}
Création d'une pizza
{% endblock %}

{% block main %}
<h2>Création d'une pizza</h2>
<form enctype="multipart/form-data" action="/pizzas/create/" method="post">
    {% csrf_token %}
    <div class="mb-3">
        <label for="id_nomPizza" class="form-label">Le nom de cette pizza</label>
        <input type="text" name="nomPizza" class="form-control" maxlength="50" required id="id_nomPizza">
    </div>
    <div class="mb-3">
        <label for="id_nomPizza" class="form-label">Le prix de cette pizza</label>
        <input type="number" name="prix" class="form-control" required id="id_nomPizza">
    </div>
    <div class="mb-3">
        <label for="id_image" class="form-label">Fichier image</label>
        <input class="form-control" name="image" type="file" accept="image/*" id="id_image">
    </div>
    <button type="submit" class="btn btn-primary">Envoyer</button>
</form>
{% endblock %}

webpizza/applipizza/templates/applipizza/formulaireModificationIngredient.html
{% extends 'applipizza/base.html' %}

{% block title %}
Modification d'un ingrédient
{% endblock %}

{% block main %}
<h2>Modification d'un ingrédient</h2>
<form action="/ingredients/{{ingredient.idIngredient}}/updated/" method="post">
    {% csrf_token %}
    <div class="mb-3">
        <label for="id_nomIngredient" class="form-label">Le nom de cet ingrédient</label>
        <input type="text" name="nomIngredient" class="form-control" maxlength="50" required id="id_nomIngredient" value="{{ingredient.nomIngredient}}">
    </div>
    <button type="submit" class="btn btn-primary">Envoyer</button>
</form>
{% endblock %}

webpizza/applipizza/templates/applipizza/formulaireModificationPizza.html
{% extends 'applipizza/base.html' %}

{% block title %}
Modification d'une pizza
{% endblock %}

{% block main %}
<h2>Modification d'une pizza</h2>
<form enctype="multipart/form-data" action="/pizzas/{{pizza.idPizza}}/updated/" method="post">
    {% csrf_token %}
    <div class="mb-3">
        <label for="id_nomPizza" class="form-label">Le nom de cette pizza</label>
        <input type="text" name="nomPizza" class="form-control" maxlength="50" required id="id_nomPizza" value="{{pizza.nomPizza}}">
    </div>
    <div class="mb-3">
        <label for="id_prix" class="form-label">Le prix de cette pizza</label>
        <input type="number" name="prix" min="0" step="0.01" class="form-control" required id="id_nomPizza" value="{{pizza.prix}}">
    </div>
    <div class="mb-3">
        <div class="divImgPizza">
            <img class="imagePizza" src="{{MEDIA_URL}}{{pizza.image}}" alt="image de pizza" title="{{pizza.nomPizza}}">
        </div>
        <div class="divNomPizza"><i>fichier actuel : {{pizza.image}}</i></div>
        Nouveau fichier image
        <input class="form-control" name="image" type="file" accept="image/*" id="id_image">
    </div>
    <button type="submit" class="btn btn-primary">Envoyer</button>
</form>
{% endblock %}

webpizza/applipizza/templates/applipizza/ingredients.html
{% extends 'applipizza/base.html' %}

{% block title %}
les ingrédients di la mama
{% endblock %}

{% block main %}
<h2>voici nos {{ingredients|length}} ingrédients</h2>
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Ingrédient</th>
            <th scope="col">Action</th>
        </tr>
    </thead>
    <tbody>
    {% for ing in ingredients %}
        <tr>
            <td scope="row">{{ing}}</td>
            <td><a href="/ingredients/{{ing.idIngredient}}/update/"><i class="bi bi-pencil-square"></i></a>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="/ingredients/{{ing.idIngredient}}/delete/"><i class="bi bi-trash"></i></a></td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% endblock %}

webpizza/applipizza/templates/applipizza/menu.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
            <img class="navbar-image" src="{% static 'applipizza/img/icon2.png' %}" alt="funny logo">
            Appli Pizza 2023
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link" href="/pizzas/">Les pizzas</a></li>
                <li class="nav-item"><a class="nav-link" href="/ingredients/">Les ingrédients</a></li>
                <li class="nav-item"><a class="nav-link" href="/ingredients/add">Créer un ingrédient</a></li>
                <li class="nav-item"><a class="nav-link" href="/pizzas/add">Créer une pizza</a></li>
            </ul>
        </div>
    </div>
</nav>

webpizza/applipizza/templates/applipizza/pizza.html
{% extends 'applipizza/base.html' %}

{% block title %}
la pizza di la mama
{% endblock %}

{% block main %}
<h2>voici NOTRE pizza</h2>
<p>{{pizza}}</p>

<div class="d-flex justify-content-center">
    <img class="imgPizza" src="{{MEDIA_URL}}{{pizza.image}}" alt="image de pizza" title="{{pizza.nomPizza}}">
</div>

{% if user.is_authenticated and not user.is_staff %}
</br>
<div class="d-flex justify-content-center">
    <a href="/pizzas/{{pizza.idPizza}}/buy/"><button class="btnAjtPanier">Ajouter au panier</button></a>
</div>
{% endif %}

</br>
{% if compo %}
<h2>voici les {{compo|length}} ingrédients de la pizza {{pizza.nomPizza}}</h2>
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Ingrédient</th>
            <th scope="col">Quantité</th>

            {% if user.is_staff %}
            <th scope="col">Supprimer</th>
            {% endif %}
        </tr>
    </thead>
    <tbody>
    {% for comp in compo %}
        <tr>
            <th>{{forloop.counter}}</th>
            <td>{{comp.ingredient}}</td>
            <td>{{comp.quantite}}</td>

            {% if user.is_staff %}
            <td><a href="/pizzas/{{pizza.idPizza}}/deleteIngredient/{{comp.idComposition}}"><span class="bi bi-trash"></span></a></td>
            {% endif %}
        </tr>
    {% endfor %}
    </tbody>
</table>
{% else %}
<p>Malheureusement, la pizza {{pizza.nomPizza}} n'a pas encore d'ingrédients</p>
{% endif %}

{% if user.is_staff %}
<h2>Ajouter un ingrédient</h2>
<form action="/pizzas/{{pizza.idPizza}}/addIngredient/" method="post">
    {% csrf_token %}
    <div class="mb-3">
        <label for="id_ingredient" class="form-label">Ingrédient</label>
        <select name="ingredient" class="form-select" required id="id_ingredient">
            <option selected disabled>choisissez</option>
            {% for ing in lesIng %}
            <option value="{{ing.idIngredient}}">{{ing.nomIngredient}}</option>
            {% endfor %}
        </select>
    </div>
    <div class="mb-3">
        <label for="id_quantite" class="form-label">Quantité</label>
        <input type="text" name="quantite" class="form-control" max-length="100" required id="id_quantite">
    </div>
    <button type="submit" class="btn btn-primary">Envoyer</button>
</form>
{% endif %}
{% endblock %}

webpizza/applipizza/templates/applipizza/pizzas.html
{% extends 'applipizza/base.html' %}

{% block title %}
les pizzas di la mama
{% endblock %}

{% block main %}
<h2>voici nos {{pizzas|length}} pizzas</h2>
<div class="d-flex justify-content-around">
    {% for piz in pizzas %}
    {% if forloop.counter0|divisibleby:3 %}
    </div>
    <div class="d-flex justify-content-around">
    {% endif %}
    <div class="divPizza">
        <div>
            <a href="/pizzas/{{piz.idPizza}}">
                <img src="{{MEDIA_URL}}{{piz.image}}" alt="image de pizza" title="{{piz.nomPizza}}">
            </a>
        </div>
        <div>{{piz}}</div>
        <div>
            <a href="/pizzas/{{piz.idPizza}}/"><i class="bi bi-info-circle"></i></a>

            {% if user.is_authenticated and not user.is_staff %}
            | 
            <a href="/pizzas/{{piz.idPizza}}/buy/"><i class="bi bi-basket"></i></a>
            {% endif %}

            {% if user.is_staff %}
            | 
            <a href="/pizzas/{{piz.idPizza}}/update/"><i class="bi bi-pencil-square"></i></a> | 
            <a href="/pizzas/{{piz.idPizza}}/delete/"><i class="bi bi-trash3"></i></a>
            {% endif %}
        </div>
    </div>
    {% endfor %}
</div>

{% endblock %}

webpizza/applipizza/templates/applipizza/traitementFormulaireCreationIngredient.html
{% extends 'applipizza/base.html' %}

{% block title %}
Ingrédient créé
{% endblock %}

{% block main %}
<h2>Création d'un ingrédient</h2>
<p>L'ingrédient {{nom}} a été créé.</p>
{% endblock %}

webpizza/applipizza/templates/applipizza/traitementFormulaireCreationPizza.html
{% extends 'applipizza/base.html' %}

{% block title %}
Pizza créé
{% endblock %}

{% block main %}
<h2>Création d'une pizza</h2>
<p>La pizza {{nom}} a été créé.</p>
{% endblock %}

webpizza/applipizza/templates/applipizza/traitementFormulaireModificationIngredient.html
{% extends 'applipizza/base.html' %}

{% block title %}
Ingrédient modifié
{% endblock %}

{% block main %}
<h2>Modification d'un ingrédient</h2>
<p>L'ingrédient {{nom}} a été modifié.</p>
{% endblock %}

webpizza/applipizza/templates/applipizza/traitementFormulaireModificationPizza.html
{% extends 'applipizza/base.html' %}

{% block title %}
Pizza modifiée
{% endblock %}

{% block main %}
<h2>Modification d'une pizza</h2>
<p>La pizza {{nom}} a été modifiée.</p>
{% endblock %}